### PR TITLE
Seats Availability --WIP

### PR DESCRIPTION
**Pull request by c-shekhar**
Added seats availability feature.
Required Args are:
- Train Number
- Source Stn Code
- Destination Stn Code
- Journey Date
- Pref Code
- Quota Code

@prinzpiuz Please, test above feature locally and let me know the changes.
I have tried merged message response(unlike multiple responses). Let me know if everything works fine.

### CODE REVIEW

**Comment by prinzpiuz** [comment]
can you short the command to just seat ?

**Comment by c-shekhar** [comment]
@prinzpiuz, sure

**Comment by prinzpiuz** [comment]
i can test it only in evening and will send you the config file via email at evening

**Comment by c-shekhar** [comment]
@prinzpiuz, that was due to my bad with message formatting!
I have tested, everything works fine now.
Still, if there are changes, let me know!

**Pull request merged**
