### PR TITLE
adding a /live command

### PR DESCRIPTION
**Pull request by drowolath**
Added a /live command for the bot.

Suggestion: it would be a good idea IMO to refactor the code a bit in order to standardise for instance returns from the API, error handling, error messages, etc.

### CODE REVIEW

**Comment by prinzpiuz** [comment]
nice work bro ...and thanks a lot

**Comment by drowolath** [comment]
Anytime !

**Comment by prinzpiuz** [comment]
you can check it now ..bot is online now....for last two months i am running it in home server....and now planning to put it in heroku

**Comment by prinzpiuz** [comment]
also i like your suggetion can you explain it little more ..since i am also beginner ...and can you help me to maintain this

**Comment by drowolath** [comment]
Just checked it: works like a charm, good job !

I'd very much appreciate helping you maintain this if you want.

Regarding my suggestion it's all about making the code modular and more readable.
For instance:
- there could be a method that is dedicated to check if the date provided has the right format and is valid
- there could be a dedicated file to constants (stations code, API urls mapped to services, ...)
- it's also possible to have your `main()` method in another file to make clear where the available functions of the bot are, and where the bot actually takes in account those functions (it can also open the way to loading those functions programmatically: anytime a new function is added and the bot is reloaded, the new function is automatically added)
- there could be a method (or class) to handle errors when status is not HTTP 200. Like this for instance:
```python
http = urllib3.PoolManager()
response = http.request('GET', something)
data = json.loads(response.data.decode('utf-8'))
if data['response_code'] == '200':
    pass # do something meaningful here
else:
    handle_error(data['reponse_code'])
```
Having a function like handle_error (it could be a method of a class too), would help IMO to deal better with errors.

How do you feel about those ideas ?

**Comment by prinzpiuz** [comment]
its fine lot of people saying me about this ....i am also planning on this ............
first want to create a telegram group for maintaining this .....there is another guy also interested in maintaining this ..............

**Pull request merged**
