### PR TITLE
Train arrivals feature

### LINKED ISSUE #11: Train arrivals
Get list of trains arriving at a station within a window period along with their live status.

### PR DESCRIPTION
**Pull request by c-shekhar**
@prinzpiuz , I have added train arrivals within a window period of 2 or 4 hours along with their live status.
Please review the PR and let me know if there are any further changes.

Fixes #11

### CODE REVIEW

**Comment by prinzpiuz** [comment]
i tested the bot with your code ... i  think arrival command not responding ...i didnt get enough time to go through your code ...so not sure about problem is in code or api...can you check it once more

**Comment by c-shekhar** [comment]
@prinzpiuz, I hope you added arrivals as command_handler.

**Comment by c-shekhar** [comment]
@prinzpiuz, now please check.

**Comment by prinzpiuz** [comment]
thank you
working fine and great job....it wasnt because of the command handler...
and one more thing is that station code is not based on number like for Ndelhi...its NDLS like this ...please update the example also
also please make a another PR for adding the working in help text 
and can you help me maintain this bot .....

**Comment by prinzpiuz** [comment]
no need of new PR i am doing it

**Comment by c-shekhar** [comment]
@prinzpiuz 
Cool, How are you planning to grow this?

**Comment by prinzpiuz** [comment]
its online now with features you added ...
i want people to use this for free
we need to plan to make it more fast and user friendly are you available in telegram

**Comment by c-shekhar** [comment]
Looks good!
I'll be happy to contribute, going forward.
This definitely needs to be user friendly.
And yes, I am big telegram fan!

**Comment by prinzpiuz** [comment]
i think we can make telegram group to manage this bot whats your telegram id

**Pull request merged**
